language: go

services:
  - docker

go:
  - "1.9"
  - "1.10"
  - "1.11"
  - "stable"

env:
  - MAKE_TASK=test-unit
  - MAKE_TASK=test-integration

before_install:
  - docker-compose up -d

install:
  - make deps

script:
  - make $MAKE_TASK

after_script:
  - docker-compose down -v
