language: go

services:
  - docker

go:
  - 1.6
  - 1.7
  - 1.8
  - master

install:
  - go get -v -d
  - go get -u github.com/onsi/ginkgo/ginkgo
  - go get -u github.com/onsi/gomega

script: ginkgo -r
