language: go

services:
  - docker

go:
  - "1.9"
  - "1.10"
  - "1.11"
  - "stable"

install:
  - go get -v -d
  - go get -u github.com/onsi/ginkgo/ginkgo
  - go get -u github.com/onsi/gomega

script: ginkgo -r
