language: go

services:
  - docker

go:
  - "1.11"
  - "1.12"
  - "stable"

env:
  - MAKE_TASK=test-unit
  - MAKE_TASK=test-integration

before_install:
  - docker-compose up -d

install:
  - make deps

script:
  - env GO111MODULE=on make $MAKE_TASK

after_script:
  - docker-compose down -v
