version: '2'
services:

  rabbitmq:
    image: rabbitmq:3.6.1-management
    ports:
      - "15672:15672"
      - "5672:5672"
      
  redis:
    image: redis

  mongo:
      image: mongo
      ports:
        - "27017:27017"
