version: '2'

services:
  db:
    image: postgres:10.3
    ports:
      - '5432:5432'
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_DB: goengine-bank
      POSTGRES_USER: goengine
      POSTGRES_PASSWORD: goengine

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
    environment:
      RABBITMQ_DEFAULT_USER: goengine
      RABBITMQ_DEFAULT_PASS: goengine
